[phases.setup]
nixPkgs = ["python312Full", "gcc", "glibc", "zlib", "libffi", "openssl", "freetype", "libpng", "pkg-config"]

[phases.install]
cmds = ["python3.12 -m pip install -r requirements.txt"]

[start]
cmd = "bash start.sh"
